triggers:
- envs: []
  name: green_taxi_etl_daily
  pipeline_uuid: green_taxi_etl
  schedule_interval: 0 5 * * *
  schedule_type: time
  settings:
    landing_time_enabled: false
  sla: null
  start_time: 2024-02-02 05:00:00
  status: active
  variables: {}
